/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.view;

import client.view.component.CustomMessageDialog;
import consts.Consts;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JSlider;
import javax.swing.ListModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import map.Map;
import model.ClientState;
import model.Room;
import model.SocketIO;

/**
 *
 * @author tienanh
 */
public class CreateRoom extends javax.swing.JFrame {
	private ClientState player;
	private SocketIO socketIO;
	private ArrayList<Map> mapsData;
    private Map selectedMap;
	
	public CreateRoom(SocketIO socketIO, ClientState player) {
        this.player = player;
        this.socketIO = socketIO;
        initComponents();
        initMapData();
		setTranparencyEffect();
		manualBindEvent();
	}
	
	public void setTranparencyEffect () {
		// Set tranparency
		jPanel2.setBackground(new Color(254, 254, 254, 30));
		jPanel3.setBackground(new Color(254, 254, 254, 30));
		jPanel4.setBackground(new Color(254, 254, 254, 30));
		
		cbGameMode.setRenderer(new DefaultListCellRenderer() {
			public void paint(Graphics g) {
				setBackground(new Color(0, 0, 0));
				setForeground(new Color(254, 254, 254));
				super.paint(g);
			};
		});
	}
	
	private void manualBindEvent() {
		jsliderSpeed.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                JSlider source = (JSlider)e.getSource();
				Integer speed = source.getValue();
					lbSpeed.setText(speed.toString());
				repaint();
            }
        });
	}
	
	public void initMapData(){
		int totalMap = consts.Consts.TOTAL_MAP;
		DefaultListModel listMapStr = new DefaultListModel();
		mapsData = new ArrayList<Map>();
		
		for (int i = 1; i < totalMap; i++){
			try {
				Class<?> clazz = Class.forName("map.Map" + i);
				listMapStr.addElement("Map" + i);
				Map map = (Map) clazz.newInstance();
				
				mapsData.add(map);
			} catch (ClassNotFoundException ex) {
				Logger.getLogger(CreateRoom.class.getName()).log(Level.SEVERE, null, ex);
			} catch (InstantiationException ex) {
				Logger.getLogger(CreateRoom.class.getName()).log(Level.SEVERE, null, ex);
			} catch (IllegalAccessException ex) {
				Logger.getLogger(CreateRoom.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
		
		mapList.setModel(listMapStr);
		registerMapListEvent();
	}


	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbSpeed = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfRoomName = new javax.swing.JTextField();
        cbGameMode = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        mapList = new javax.swing.JList<>();
        jsliderSpeed = new javax.swing.JSlider();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mapSizeField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        mapDesField = new javax.swing.JTextArea();
        imagePreview = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setMinimumSize(new java.awt.Dimension(1200, 800));

        jPanel1.setBackground(new java.awt.Color(228, 228, 228));
        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 800));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 800));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(171, 171, 171));

        jLabel2.setFont(new java.awt.Font("LifeCraft", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Create Game");

        jLabel3.setFont(new java.awt.Font("LifeCraft", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(236, 202, 47));
        jLabel3.setText("Game Speed:");

        jLabel4.setFont(new java.awt.Font("LifeCraft", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(236, 202, 47));
        jLabel4.setText("Select Map");

        lbSpeed.setBackground(new java.awt.Color(1, 1, 1));
        lbSpeed.setFont(new java.awt.Font("LifeCraft", 0, 24)); // NOI18N
        lbSpeed.setForeground(new java.awt.Color(236, 202, 47));
        lbSpeed.setText("5");
        lbSpeed.setOpaque(true);
        lbSpeed.setPreferredSize(new java.awt.Dimension(20, 24));

        jLabel8.setFont(new java.awt.Font("LifeCraft", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(236, 202, 47));
        jLabel8.setText("Game Mode");

        jLabel1.setFont(new java.awt.Font("LifeCraft", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 202, 47));
        jLabel1.setText("Room Name");

        tfRoomName.setBackground(new java.awt.Color(1, 1, 1));
        tfRoomName.setForeground(new java.awt.Color(254, 254, 254));

        cbGameMode.setBackground(new java.awt.Color(1, 1, 1));
        cbGameMode.setFont(new java.awt.Font("LifeCraft", 0, 18)); // NOI18N
        cbGameMode.setForeground(new java.awt.Color(254, 254, 254));
        cbGameMode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2 Ball", "1 Ball" }));
        cbGameMode.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbGameMode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbGameModeMouseClicked(evt);
            }
        });
        cbGameMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGameModeActionPerformed(evt);
            }
        });

        mapList.setBackground(new java.awt.Color(1, 1, 1));
        mapList.setForeground(new java.awt.Color(254, 254, 254));
        jScrollPane1.setViewportView(mapList);

        jsliderSpeed.setBackground(new java.awt.Color(1, 1, 1));
        jsliderSpeed.setMaximum(10);
        jsliderSpeed.setToolTipText("");
        jsliderSpeed.setValue(5);
        jsliderSpeed.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbGameMode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfRoomName)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4))
                        .addGap(0, 539, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                    .addComponent(jsliderSpeed, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfRoomName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsliderSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbGameMode, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(12, 12, 720, 770);

        jPanel3.setBackground(new java.awt.Color(154, 154, 154));

        jLabel5.setFont(new java.awt.Font("LifeCraft", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 202, 47));
        jLabel5.setText("Map Description:");

        jLabel6.setFont(new java.awt.Font("LifeCraft", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(236, 202, 47));
        jLabel6.setText("Suggested Players:");

        jLabel7.setFont(new java.awt.Font("LifeCraft", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(236, 202, 47));
        jLabel7.setText("Map Size:");

        mapSizeField.setEditable(false);
        mapSizeField.setBackground(new java.awt.Color(1, 1, 1));
        mapSizeField.setForeground(new java.awt.Color(254, 254, 254));
        mapSizeField.setText("Medium");

        mapDesField.setBackground(new java.awt.Color(1, 1, 1));
        mapDesField.setColumns(20);
        mapDesField.setForeground(new java.awt.Color(254, 254, 254));
        mapDesField.setLineWrap(true);
        mapDesField.setRows(5);
        mapDesField.setText("Map Created By: Tanker\nMore infomation at: \nhttps://github.com/tienanhnguyen191999/BTL_LapTrinhMang \t");
        jScrollPane2.setViewportView(mapDesField);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(1, 1, 1));
        jTextField1.setForeground(new java.awt.Color(254, 254, 254));
        jTextField1.setText("10");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imagePreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(mapSizeField, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))))
                .addGap(468, 468, 468))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagePreview, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(mapSizeField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(749, 16, 440, 600);

        jPanel4.setBackground(new java.awt.Color(253, 207, 161));

        jButton1.setBackground(new java.awt.Color(1, 1, 1));
        jButton1.setFont(new java.awt.Font("LifeCraft", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(254, 254, 254));
        jButton1.setText("Create Game");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(254, 254, 254)));
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setOpaque(true);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(1, 1, 1));
        jButton2.setFont(new java.awt.Font("LifeCraft", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(254, 254, 254));
        jButton2.setText("Cancel");
        jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(254, 254, 254)));
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setOpaque(true);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(749, 630, 440, 150);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/image/bacground_1200x800.jpeg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 0, 1200, 800);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if (tfRoomName.getText().isEmpty()){
				new CustomMessageDialog().showMessage("Room Name Required");
                return;
            }
			
			if ( selectedMap == null) {
				new CustomMessageDialog().showMessage("No Map Selected");
				return;
			}
			
			// GameMode
			int gameMode = Consts.TWO_BALL;
			if (cbGameMode.getSelectedItem().toString().toLowerCase().trim().equals("1 ball")) {
				gameMode = Consts.ONE_BALL;
			}
			
            // 1. Send Action_Code
            socketIO.getOutput().writeObject(Consts.CREATE_ROOM_CODE);
			
            // 2. Send Data
            Room newRoom = new Room();
            newRoom.setP1(player);
            newRoom.setMap(selectedMap);
            newRoom.setName(tfRoomName.getText().trim());
            newRoom.setSpeed(jsliderSpeed.getValue());
			newRoom.setGameMode(gameMode);
            socketIO.getOutput().writeObject(newRoom);
            // Check if room name is register
            boolean isRoomNameUnique = (boolean)socketIO.getInput().readObject();
            if (isRoomNameUnique){
                this.dispose();
                new PrepareGame(socketIO, newRoom, true).setVisible(true);
            }else{
				new CustomMessageDialog().showMessage("Room Name is Registered");
                return;
            }
        } catch (IOException ex) { 
            Logger.getLogger(CreateRoom.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CreateRoom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

	private void registerMapListEvent() {
		mapList.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent arg0) {
                if (!arg0.getValueIsAdjusting()) {
					try {
						String mapName = mapList.getSelectedValue().trim();
						Class<?> clazz = Class.forName("map." + mapName);
						selectedMap = (Map) clazz.newInstance();
                        
						ImageIcon icon = new ImageIcon(getClass().getResource(selectedMap.getMapInfo().getImagePreviewPath())); 
						Image resize = icon.getImage().getScaledInstance(imagePreview.getWidth(), imagePreview.getHeight(), Image.SCALE_SMOOTH);
						ImageIcon result = new ImageIcon(resize);
						imagePreview.setIcon(result);
						mapSizeField.setText(selectedMap.getMapInfo().getType());
						mapDesField.setText(selectedMap.getMapInfo().getDes());
                        
					} catch (ClassNotFoundException ex) {
						Logger.getLogger(CreateRoom.class.getName()).log(Level.SEVERE, null, ex);
					} catch (InstantiationException ex) {
						Logger.getLogger(CreateRoom.class.getName()).log(Level.SEVERE, null, ex);
					} catch (IllegalAccessException ex) {
						Logger.getLogger(CreateRoom.class.getName()).log(Level.SEVERE, null, ex);
					}
                }
            }
        });
	}
	
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		this.dispose();
		boolean isRegisterName = true;
		new LAN(socketIO, player, isRegisterName).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        addHoverEffect(jButton1);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        removeHoverEffect(jButton2);
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        addHoverEffect(jButton2);
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        removeHoverEffect(jButton1);
    }//GEN-LAST:event_jButton1MouseExited

    private void cbGameModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGameModeActionPerformed

    }//GEN-LAST:event_cbGameModeActionPerformed

    private void cbGameModeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbGameModeMouseClicked
		repaint(); // windows issue
    }//GEN-LAST:event_cbGameModeMouseClicked

	public void addHoverEffect (JButton jButton) {
		jButton.setForeground(new Color(0, 0, 0));
		jButton.setBackground(new Color(254, 254, 254));
	}
	
	public void removeHoverEffect (JButton jButton) {
		jButton.setForeground(new java.awt.Color(254, 254, 254));
		jButton.setBackground(new Color(0, 0, 0));
	}
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbGameMode;
    private javax.swing.JLabel imagePreview;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JSlider jsliderSpeed;
    private javax.swing.JLabel lbSpeed;
    private javax.swing.JTextArea mapDesField;
    private javax.swing.JList<String> mapList;
    private javax.swing.JTextField mapSizeField;
    private javax.swing.JTextField tfRoomName;
    // End of variables declaration//GEN-END:variables
}

